[package]
name = "rustique"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["android-native-activity"] }
wgpu = "24.0.1"
env_logger = "0.11.6"
log = "0.4.25"
pollster = "0.4.0"